public class VariablesTheme {

    public static void main(String[] args) {
        System.out.println("ЗАДАЧА 1");
        byte CPU = 8;
        short RAM = 16;
        int RAM2 = 3600;
        long HDD = 40000;
        float power = 800.00f;
        double cost = 70.500;
        char CPU_char = 'i';
        boolean play = true;
        System.out.println("Процессор: Intel Core " + CPU_char + "7;");
        System.out.println("Количество ядер: " + CPU + ";");
        System.out.println("Оперативная память: " + RAM + " GGB DDR4 с частотой от " + RAM2
                + " Мгц;");
        System.out.println("Место на диске: " + HDD + " Мб;");
        System.out.println("Мощность БП: " + power + " Вт;");
        System.out.println("Игровой: " + play + ";");
        System.out.println("Цена: " + cost + ";");
        System.out.println();
        System.out.println("ЗАДАЧА 2");
        int book = 200;
        int pen = 100;
        float cell = 11;
        int total = book + pen;
        float total_cell = total - ((total * cell) / 100);
        System.out.println("Общая стоимость товаров: " + total);
        System.out.println("Сумма скидки: " + (total * cell) / 100);
        System.out.println("Общая стоимость товаров со скидкой: " + total_cell);
        System.out.println();
        System.out.println("ЗАДАЧА 3");
        System.out.println("   J    a  v     v  a   ");
        System.out.println("   J   a a  v   v  a a  ");
        System.out.println("J  J  aaaaa  V V  aaaaa ");
        System.out.println(" JJ  a     a  V  a     a");
        System.out.println();
        System.out.println("ЗАДАЧА 4");
        byte byte01 = 127;
        short short01 = 32767;
        int int01 = 2147483647;
        long long01 = 9223372036854775807l;
        System.out.println("Первоначальное значение " + byte01 + " Значение после инкремента " + 
                ++byte01 + " Значение после декремента " + --byte01);
        System.out.println("Первоначальное значение " + short01 + " Значение после инкремента " + 
                ++short01 + " Значение после декремента " + --short01);
        System.out.println("Первоначальное значение " + int01 + " Значение после инкремента " + 
                ++int01 + " Значение после декремента " + --int01);
        System.out.println("Первоначальное значение " + long01 + " Значение после инкремента " + 
                ++long01 + " Значение после декремента " + --long01);
        System.out.println();
        System.out.println("ЗАДАЧА 5");
        int a = 2;
        int b = 5;
        int c;
        System.out.println("С помощью третьей переменной");
        System.out.println("исходные значения: a =" + a + " b = " + b);
        c = a;
        a = b;
        b = c;
        System.out.println("новые значения: a =" + a + " b = " + b);
        System.out.println("С помощью арифметических операций");
        a = 2;
        b = 5;
        System.out.println("исходные значения: a =" + a + " b = " + b);
        a = a + b;
        b = a - b;
        a = a - b;
        System.out.println("новые значения: a =" + a + " b = " + b);
        System.out.println("С помощью побитовой операции");
        a = 2;
        b = 5;
        System.out.println("исходные значения: a =" + a + " b = " + b);
        a = a ^ b;
        b = b ^ a;
        a = a ^ b;
        System.out.println("новые значения: a =" + a + " b = " + b);
        System.out.println();
        System.out.println("ЗАДАЧА 6");
        char ch1 = '#';
        int int1 = 35;
        char ch2 = '&';
        int int2 = 38;
        char ch3 = '@';
        int int3 = 64;
        char ch4 = '^';
        int int4 = 94;
        char ch5 = '_';
        int int5 = 95;
        System.out.printf(int1 + " " + ch1 + "\n");
        System.out.printf(int2 + " " + ch2 + "\n");
        System.out.printf(int3 + " " + ch3 + "\n");
        System.out.printf(int4 + " " + ch4 + "\n");
        System.out.printf(int5 + " " + ch5 + "\n");
        System.out.println();
        System.out.println("ЗАДАЧА 7");
        char symbol1 = '/';
        char symbol2 = '_';
        char symbol3 = '(';
        char symbol4 = ')';
        char symbol5 = '\\';
        System.out.println("     " + symbol1 + "" + symbol5);
        System.out.println("    " + symbol1 + "  " + symbol5);
        System.out.println("   " + symbol1 + "" + symbol2 + "" + symbol3 + " " + symbol4 + symbol5);
        System.out.println("  " + symbol1 + "      " + symbol5);
        System.out.println(" " + symbol1 + "" + symbol2 + "" + symbol2 + "" + symbol2 + "" + symbol2
                + "" + symbol1 + "" + symbol5 + "" + symbol2 + "" + symbol2 + "" + symbol5);
        System.out.println();
        System.out.println("ЗАДАЧА 8");
        int number = 123;
        int x, y, z;
        x = number % 1000 / 100;
        y = number % 100 / 10;
        z = number % 10;
        int sum_number = x + y + z;
        int increase_num = x * y * z;
        System.out.println("Число " + number + " содержит:");
        System.out.println(x + " сотен");
        System.out.println(y + " десятков");
        System.out.println(z + " едениц");
        System.out.println("Сумма его цифр = " + sum_number);
        System.out.println("Произведение его цифр = " + increase_num);
        System.out.println();
        System.out.println("ЗАДАЧА 9");
        int num = 86399;
        int hour = (num / 3600);
        int minutes = num / 60 % 60;
        int seconds = num / 1 % 60;
        System.out.println(hour + ":" + minutes + ":" + seconds);
    }
}
