public class VariablesTheme {

    public static void main(String[] args) {
        System.out.println("1. Вывод значений переменных на консоль");
        byte cpu = 8;
        short ram = 16;
        int freq = 3600;
        long hdd = 40000;
        float power = 800.00f;
        double cost = 70.500;
        char cpuIndex = 'i';
        boolean play = true;
        System.out.println("Процессор: Intel Core " + cpuIndex + "7;");
        System.out.println("Количество ядер: " + cpu + ";");
        System.out.println("Оперативная память: " + ram + " GGB DDR4 с частотой от " + freq
                + " Мгц;");
        System.out.println("Место на диске: " + hdd + " Мб;");
        System.out.println("Мощность БП: " + power + " Вт;");
        System.out.println("Игровой: " + play + ";");
        System.out.println("Цена: " + cost + ";");
        System.out.println("\n2. Расчет стоимости товара со скидкой");
        int book = 200;
        int pen = 100;
        float cell = 11;
        int total = book + pen;
        float total_cell = total - ((total * cell) / 100);
        System.out.println("Общая стоимость товаров: " + total);
        System.out.println("Сумма скидки: " + (total * cell) / 100);
        System.out.println("Общая стоимость товаров со скидкой: " + total_cell);
        System.out.println("\n3. Вывод слова JAVA");
        System.out.println("   J    a  v     v  a   ");
        System.out.println("   J   a a  v   v  a a  ");
        System.out.println("J  J  aaaaa  V V  aaaaa ");
        System.out.println(" JJ  a     a  V  a     a");
        System.out.println("\n4. Вывод min и max значений целых числовых типов");
        byte byteMax = 127;
        short shortMax = 32767;
        int intMax = 2147483647;
        long longMax = 9223372036854775807l;
        System.out.println("Первоначальное значение " + byteMax + ". Значение после инкремента = " +
                ++byteMax + ". Значение после декремента = " + --byteMax);
        System.out.println("Первоначальное значение " + shortMax + ". Значение после инкремента = "
                + ++shortMax + ". Значение после декремента = " + --shortMax);
        System.out.println("Первоначальное значение " + intMax + ". Значение после инкремента = " +
                ++intMax + ". Значение после декремента = " + --intMax);
        System.out.println("Первоначальное значение " + longMax + ". Значение после инкремента = " +
                ++longMax + ". Значение после декремента = " + --longMax);
        System.out.println("\n5. Перестановка значений переменных");
        int var1 = 2;
        int var2 = 5;
        int var3;
        System.out.println("С помощью третьей переменной");
        System.out.println("исходные значения: a = " + var1 + " b = " + var2);
        var3 = var1;
        var1 = var2;
        var2 = var3;
        System.out.println("новые значения: a = " + var1 + " b = " + var2);
        System.out.println("С помощью арифметических операций");
        var1 = 2;
        var2 = 5;
        System.out.println("исходные значения: a = " + var1 + " b = " + var2);
        var1 = var1 + var2;
        var2 = var1 - var2;
        var1 = var1 - var2;
        System.out.println("новые значения: a = " + var1 + " b = " + var2);
        System.out.println("С помощью побитовой операции");
        var1 = 2;
        var2 = 5;
        System.out.println("исходные значения: a = " + var1 + " b = " + var2);
        var1 = var1 ^ var2;
        var2 = var2 ^ var1;
        var1 = var1 ^ var2;
        System.out.println("новые значения: a = " + var1 + " b = " + var2);
        System.out.println("\n6. Вывод символов и их кодов");
        char ch1 = '#';
        int int1 = 35;
        char ch2 = '&';
        int int2 = 38;
        char ch3 = '@';
        int int3 = 64;
        char ch4 = '^';
        int int4 = 94;
        char ch5 = '_';
        int int5 = 95;
        System.out.printf(int1 + " " + ch1 + "\n");
        System.out.printf(int2 + " " + ch2 + "\n");
        System.out.printf(int3 + " " + ch3 + "\n");
        System.out.printf(int4 + " " + ch4 + "\n");
        System.out.printf(int5 + " " + ch5 + "\n");
        System.out.println("\n7. Вывод в консоль ASCII-арт Дюка");
        char symbol1 = '/';
        char symbol2 = '_';
        char symbol3 = '(';
        char symbol4 = ')';
        char symbol5 = '\\';
        System.out.println("     " + symbol1 + "" + symbol5);
        System.out.println("    " + symbol1 + "  " + symbol5);
        System.out.println("   " + symbol1 + "" + symbol2 + "" + symbol3 + " " + symbol4 + symbol5);
        System.out.println("  " + symbol1 + "      " + symbol5);
        System.out.println(" " + symbol1 + "" + symbol2 + "" + symbol2 + "" + symbol2 + "" + symbol2
                + "" + symbol1 + "" + symbol5 + "" + symbol2 + "" + symbol2 + "" + symbol5);
        System.out.println("\n8. Вывод количества сотен, десятков и единиц числа");
        int number = 123;
        int rank1, rank2, rank3;
        rank1 = number % 1000 / 100;
        rank2 = number % 100 / 10;
        rank3 = number % 10;
        int sum_number = rank1 + rank2 + rank3;
        int increase_num = rank1 * rank2 * rank3;
        System.out.println("Число " + number + " содержит:");
        System.out.println(rank1 + " сотню");
        System.out.println(rank2 + " десятка");
        System.out.println(rank3 + " еденицы");
        System.out.println("Сумма его цифр = " + sum_number);
        System.out.println("Произведение его цифр = " + increase_num);
        System.out.println("\n9. Вывод времени");
        int num = 86399;
        int hour = (num / 3600);
        int minutes = num / 60 % 60;
        int seconds = num / 1 % 60;
        System.out.println(hour + ":" + minutes + ":" + seconds);
    }
}